KEYWORDS = [
    'ALL',
    'ALTER',
    'ANY',
    'AS',
    'ASC',
    'BEGIN',
    'BY',
    'CREATE',
    'CONTINUOUS QUERY',
    'CONTINUOUS QUERIES',
    'DATABASE',
    'DATABASES',
    'DEFAULT',
    'DELETE',
    'DESC',
    'DESTINATIONS',
    'DIAGNOSTICS',
    'DISTINCT',
    'DROP',
    'DURATION',
    'END',
    'EVERY',
    'EXPLAIN',
    'FIELD KEY',
    'FIELD KEYS',
    'FOR',
    'FROM',
    'GRANT',
    'GRANTS',
    'GROUP',
    'GROUPS',
    'IN',
    'INF',
    'INSERT',
    'INTO',
    'KEY',
    'KEYS',
    'KILL',
    'LIMIT',
    'SHOW',
    'MEASUREMENT',
    'MEASUREMENTS',
    'NAME',
    'OFFSET',
    'ON',
    'ORDER',
    'PASSWORD',
    'PRIVILEGES',
    'QUERIES',
    'QUERY',
    'READ',
    'REPLICATION',
    'RESAMPLE',
    'RETENTION POLICY',
    'RETENTION POLICIES',
    'REVOKE',
    'SELECT',
    'SERIES',
    'SET',
    'SHARD',
    'SHARDS',
    'SHARD DURATION',
    'SHARD GROUPS',
    'SLIMIT',
    'SOFFSET',
    'STATS',
    'SUBSCRIPTION',
    'SUBSCRIPTIONS',
    'TAG KEY',
    'TAG KEYS',
    'TAG VALUES',
    'TO',
    'USER',
    'USERS',
    'VALUES',
    'WHERE',
    'WITH',
    'WRITE',
]
