KEYWORDS = [
    'ALL',
    'ALTER',
    'ANY',
    'AS',
    'ASC',
    'BEGIN',
    'BY',
    'CREATE',
    'CONTINUOUS QUERY',
    'CONTINUOUS QUERIES',
    'DATABASE',
    'DATABASES',
    'DEFAULT',
    'DELETE',
    'DESC',
    'DESTINATIONS',
    'DIAGNOSTICS',
    'DISTINCT',
    'DROP',
    'DURATION',
    'END',
    'EVERY',
    'EXPLAIN',
    'FIELD KEY',
    'FIELD KEYS',
    'FOR',
    'FROM',
    'GRANT',
    'GRANTS',
    'GROUP',
    'GROUPS',
    'IN',
    'INF',
    'INSERT',
    'INTO',
    'KEY',
    'KEYS',
    'KILL',
    'LIMIT',
    'SHOW',
    'MEASUREMENT',
    'MEASUREMENTS',
    'NAME',
    'OFFSET',
    'ON',
    'ORDER',
    'PASSWORD',
    'PRIVILEGES',
    'QUERIES',
    'QUERY',
    'READ',
    'REPLICATION',
    'RESAMPLE',
    'RETENTION POLICY',
    'RETENTION POLICIES',
    'REVOKE',
    'SELECT',
    'SERIES',
    'SET',
    'SHARD',
    'SHARDS',
    'SHARD DURATION',
    'SHARD GROUPS',
    'SLIMIT',
    'SOFFSET',
    'STATS',
    'SUBSCRIPTION',
    'SUBSCRIPTIONS',
    'TAG KEY',
    'TAG KEYS',
    'TAG VALUES',
    'TO',
    'USE',
    'USER',
    'USERS',
    'VALUES',
    'WHERE',
    'WITH',
    'WRITE',
]

FUNCTIONS = [
    'BOTTOM()',
    'CEILING()',
    'COUNT()',
    'CUMULATIVE_SUM()',
    'DERIVATIVE()',
    'DIFFERENCE()',
    'DISTINCT()',
    'ELAPSED()',
    'FIRST()',
    'FLOOR()',
    'HISTOGRAM()',
    'HOLT_WINTERS()',
    'INTEGRAL()',
    'LAST()',
    'MAX()',
    'MEAN()',
    'MEDIAN()',
    'MIN()',
    'MODE()',
    'MOVING_AVERAGE()',
    'NON_NEGATIVE_DERIVATIVE()',
    'NON_NEGATIVE_DIFFERENCE()',
    'PERCENTILE()',
    'SAMPLE()',
    'SPREAD()',
    'STDDEV()',
    'SUM()',
    'TOP()',
]
