sudo: required

services:
  - docker

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - docker pull influxdb:latest
  - docker run -t -d -p 8086:8086 influxdb

install:
  - pip install pipenv
  - pip install codecov
  - pipenv install --dev --three
  - pipenv shell

script:
  - tox

after_success:
  - codecov
