sudo: required

services:
  - docker

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - docker pull influxdb:1.8
  - docker run -t -d -p 8086:8086 influxdb

install:
  - pip install pathlib2
  - pip install pipenv -U
  - pipenv install --dev
  - pipenv graph

script:
  - pytest -v

after_success:
  - codecov
